### ISSUE TITLE
Update to most 0.18.6?

### ISSUE THREAD

**Issue by axefrog** [motorcyclejs/core#52]
Just updated myself and noticed it broke Motorcycle. Something to do with most-subject and the lack of `MulticastSource`.

```text
Error: Cannot find module 'most/lib/source/MulticastSource' from 'D:\snip\node_modules\most-subject\lib'
    at D:\snip\node_modules\resolve\lib\async.js:46:17
    at process (D:\snip\node_modules\resolve\lib\async.js:173:43)
    at ondir (D:\snip\node_modules\resolve\lib\async.js:188:17)
    at load (D:\snip\node_modules\resolve\lib\async.js:69:43)
    at onex (D:\snip\node_modules\resolve\lib\async.js:92:31)
    at D:\snip\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by TylorS** [comment]
Yes, this is something I definitely need to do

**Comment by axefrog** [comment]
Also, I just ran a fresh reinstall of the motorcycle and related packages:

```
npm install --save @most/hold @motorcycle/core @motorcycle/dom @motorcycle/history @motorcycle/html @motorcycle/http @motorcycle/router history most
```

The following warnings were reported

```text
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.9
npm WARN @motorcycle/history@2.1.1 requires a peer of @motorcycle/core@1.1.0 but none was installed.
npm WARN @motorcycle/history@2.1.1 requires a peer of history@2.0.0 but none was installed.
npm WARN @motorcycle/http@2.2.0 requires a peer of @motorcycle/core@1.1.0 but none was installed.
npm WARN @motorcycle/router@1.2.1 requires a peer of @motorcycle/core@1.1.0 but none was installed.
```

**Comment by axefrog** [comment]
Actually, in follow-up to that, if `@most/hold` is installed explicitly, it looks like the multicast issue shows up by default, so as it stands, you won't be able to recommend that package to anyone in conjunction with Motorcycle; you'd have to rely on Motorcycle installing it as a dependency and then just use that as though it'd been installed directly.

**Comment by TylorS** [comment]
Thank you for the info, I'll try to fix this stuff soon

**Comment by TylorS** [comment]
This is done now! Thank you @axefrog!
